### ISSUE TITLE
Peformance: Ansible Container image build takes too long 

### ISSUE THREAD

**Issue by chrisheaththomas** [ansible/ansible-container#122]
This seems to be recognised with the "(please be patient)" message. However, developers are not patient, nor should they be. Ansible Container build needs to be much faster as it is executed each time in the build/run/test cycle.

**Comment by ReeSilva** [comment]
@chrisheaththomas I agree. I believe that the main cause of this is because Ansible Container build a builder image. 

My doubt, obviously, to the Ansible-Container team is: there is any problem in you guys supply the builder by an already compiled image on Docker Hub or any other place? There is a REALLY need on build the image builder everytime? Why not instead of this, put the playbook "on the" container by a volume instruction on container.yml (and, obviously, give to us devs the power to supply infos to the builder image on this file)?

**Comment by gregdek** [comment]
Yes. We're aware, and this will be the first key area of performance improvement. 

A couple of things:

* We *will* have a pre-built image on Dockerhub when we release the first official version of this, so that will mitigate some of this.
* A lot of the problem is that it's not apparent what's going on. What's taking all the time? Why aren't we spitting that info out, so the user can at the very least see what's taking all the cycles? We need to figure this out.

**Comment by chouseknecht** [comment]
The builder image is in place. There is an open issue (#143) for adding a build cache mechanism, which I believe addresses the remaining issues.
