### ISSUE TITLE
ansible-container build --flatten destroys metadata

### ISSUE THREAD

**Issue by eaceaser** [ansible/ansible-container#169]
##### ISSUE TYPE

 - Bug / Documentation Report

##### container.yml 

Any container metadata:
```
    environment:
       ...
    expose:
      - some
      - ports
```

##### main.yml 
n/a

##### OS / ENVIRONMENT

```
Ansible Container, version 0.1.0
Darwin, straylight.faunadb.net, 15.6.0, Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64, x86_64
2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] /usr/local/opt/python/bin/python2.7
```
##### SUMMARY
Because --flatten uses the docker export / import pattern to remove all layers from an image, it also loses all metadata. This includes environment variables, exposed ports, and image entrypoints / commands.

##### STEPS TO REPRODUCE

```
docker build --flatten
```

##### EXPECTED RESULTS
The documentation for this command should indicate that all metadata is lost, but, honestly, its unclear whether or not the image is even useful without metadata.

**Comment by chouseknecht** [comment]
This does look like a problem. Tested using postgres:9.5 as the base image, since it has exposed ports, cmd, env, volumes, etc.

container.yml:

```
version: "1"
services:
  sleepy:
    image: 'postgres:9.5'
    command: ['sleep', '1d']

registries: {}
```
 
main.yml:

```
- hosts: sleepy
  gather_facts: no
  tasks:
```

Beginning Config from the base image:

```
"Config": {
            "Hostname": "2da0903ff372",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/lib/postgresql/9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "LANG=en_US.utf8",
                "PG_MAJOR=9.5",
                "PG_VERSION=9.5.4-1.pgdg80+1",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Cmd": [
                "postgres"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:0e577940fabd67262fdc14d6b5517d9970dd1fab63102a9e954e3d198fd85fb5",
            "Volumes": {
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
```

Below is the image Config after `ansible-container build`, which as expected is a merge of the base image with a couple minor changes from container.yml:

```
"Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/lib/postgresql/9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "LANG=en_US.utf8",
                "PG_MAJOR=9.5",
                "PG_VERSION=9.5.4-1.pgdg80+1",
                "PGDATA=/var/lib/postgresql/data"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "sleep 1d"
            ],
            "Image": "",
            "Volumes": {
                "/var/lib/postgresql/data": {}
            },
            "WorkingDir": "/",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "5cece081a4e281b94d9fa7f4634bc7cb5dbd01129d0882f6b80b72b66fcd480b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ansible",
                "com.docker.compose.service": "sleepy",
                "com.docker.compose.version": "1.7.0"
            }
        },
```

And here it is post `ansible-container build --flatten` where it indeed appears all the meta data has been lost:

```
"Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
```

**Comment by chouseknecht** [comment]
@joobar - 

I noodled on this a bit. It seems the only way to restore the meta data is to do the following in the post build steps: 

- Get the Config from an inspection of the container being exported
- Merge the Config data with the command, workdir, user, etc from the container.yml service 
- Translate the Config to Dockerfile commands
- Start a container from the exported image
- Perform a commit of the container passing in the set of Dockerfile commands 

Translating the Config to Dockerfile is not entirely simple. It can be done, but things like Volumes and Cmd will take some thought. Also, not everything in config translates to a Dockerfile directive. Examples include: hostname, domainname, attachstdin, attachstderr, etc, so there will still be some meta data lost.

Something to note - if we do this, we end up 2 layers rather than 1. I don't know that having 2 layers is horrible, just something to know.

**Comment by j00bar** [comment]
I'm rather `WONTFIX` on this one. Flattening is a standard Docker procedure of exporting and reimporting from tarball, which, yes, destroys metadata. If there's a better way to squash layers that doesn't destroy the metadata, I'm all ears, but at most I believe this should simply be a documented side-effect.

**Comment by vrutkovs** [comment]
>If there's a better way to squash layers that doesn't destroy the metadata, I'm all ears, but at most I believe this should simply be a documented side-effect.

There is https://github.com/goldmann/docker-squash, it has an option to squash several layers (e.g. base image + all other layers)

**Comment by chouseknecht** [comment]
Updated reference documentation with a note stating that a side effect of *--flatten* is loss of image metadata.
