### ISSUE TITLE
should we relabel selinux labels on docker.sock

### ISSUE THREAD

**Issue by dustymabe** [ansible/ansible-container#192]
If you don't supply a DOCKER_HOST then we assume /var/run/docker.sock. We also bind mount this into the container in several places:

```
{% if not env.DOCKER_HOST %}- /var/run/docker.sock:/tmp/docker.sock:Z{% endif %}
```

This will change the label of /var/run/docker.sock from `system_u:object_r:docker_var_run_t:s0` to `system_u:object_r:svirt_sandbox_file_t:s0:c550,c614`. I suspect what we actually want to do here is not change the label on the docker socket, but make the container run as a privileged container in this case so that it can access the socket without violating selinux policy.

**Comment by dustymabe** [comment]
@rhatdan could you comment on this? The question is: "is it better to run with `:Z` on bind mounted `/var/run/docker.sock` or run the container as a privileged container?"

**Comment by rhatdan** [comment]
Run as a privileged container.  You should never relabel key infrastructure.  Just allowing the docker.sock to be used is not enough to allow a confined domain to talk to the docker daemon.  You would also need to allow svirt_lxc_net_t to `connectto` docker_t. 

Once a domain is allowed to talk to the docker_t dameon, it has full root access to the host machine, since it could just do the equivalent of 
docker run --privileged -v /:/host fedora chroot /host
