### ISSUE TITLE
Killing containers after playbook execution?

### ISSUE THREAD

**Issue by containscafeine** [ansible/ansible-container#200]
##### ISSUE TYPE
 - Feature Idea?

Hey,

After the playbook has finished executing on the base image during the build process, the containers are stopped (not killed) and then committed.

This stopping of containers takes a bit of time. Does it make sense to kill the containers and then commit them, to speed up the process? I hope this is not bad practice.

Feedback? Thoughts?

**Comment by j00bar** [comment]
Killing the containers does not allow their processes to execute shutdown procedures, such as cleaning up locks or leaving databases in known states. I'd prefer not to make an image from a container that's been killed versus cleanly shut down. I'm happy to hear arguments otherwise. Thanks!

**Comment by dustymabe** [comment]
I agree that graceful shutdown is more desirable than killing things off. However I think that we probably shouldn't be starting long running processes as part of the "build" phase so really nothing should need to be killed. We really should be running some tasks that run-to-completion and then exit.

**Comment by chouseknecht** [comment]
IMHO, to not raise red flags and to avoid making assumptions about what may or may not be running in containers, we should *stop* containers unless the user indicates otherwise.

That being said, during the build process, those hosts returned by *listhosts* are started with the command "sleep 1d" (or something like that). In this one instance we know exactly what process is running, and we *could* kill the container. But, it still seems like bad form.
