### ISSUE TITLE
Builder container run briefly and exits when running "ansible-container run"

### ISSUE THREAD

**Issue by djfang** [ansible/ansible-container#309]
##### ISSUE TYPE

 - Documentation Report

I just have a quick question. I realized that when I run `ansible-container run`, the builder container runs briefly and then exists. Everything seems to still run fine after, just curious why this is the behavior, does the builder container need to do anything at before it exits?

Couldn't find much info on this.

Any guidance will be appreciated it.

Thanks!

**Comment by chouseknecht** [comment]
The build container runs on almost every command so that we can get the set of hosts impacted by the playbook. We only run Ansible commands inside the build container. We do not run them outside. And so to get the set of hosts, it starts the build container and then runs something like `ansible-playbook --list-hosts main.yml`.

**Comment by djfang** [comment]
@chouseknecht Got it. Thanks for the clarification!
