### ISSUE TITLE
Embody container lifecycle through Ansible playbook operations

### ISSUE THREAD

**Issue by gregdek** [ansible/ansible-container#377]
From jag's email to Ansible Container list of 29 January 2017:

We find ourselves needing more and more functionality inside of the “builder” container, to the point that we’re giving in and trying to shift the majority of the functionality into the builder container. This will make the “Engine” class that much simpler, making other container engine integrations easier to write.

**Comment by gregdek** [comment]
"Moving functionality into conductor is ongoing. Config, which I'm working on, is a big part of that." --jag 1 March

**Comment by j00bar** [comment]
@ryansb and @chouseknecht - 

So Ryan and I discussed out of band and agreed that even otherwise trivial operations like stop/start/restart/destroy that would likely be completely doable without the Conductor will be done as Ansible playbooks.

The reason I'm +1 on that, and the "target goal" for this ticket, is having start/stop/restart/destroy/run/deploy actually all create the _same_ playbook, but with differently tagged tasks, but capable of outlining the entire lifecycle management for the containers in question. This will increase our value/utility and simplify the codepaths for Ansible playbook generation.

-jag

**Comment by ryansb** [comment]
Combined with artifact output, this means that users could either let the conductor run playbooks, or run them themselves with tags like `ansible-playbook main.yml --tags run`

**Comment by gregdek** [comment]
Update from ryansb: "it's all working now, so the 'embody lifecycle' bit is just rearranging how I build the playbooks" -- should be ready for release
