### ISSUE TITLE
Cannot get anything to run

### ISSUE THREAD

**Issue by Sean-Brown** [ansible/ansible-container#483]
##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
I installed ansible-container as directed: `sudo pip install ansible-container`
That installed successfully.
I run `ansible-container init`, which succeeds, then `ansible-container build`, which gets the following error: 
> ImportError: You must install Ansible Container with Docker(tm) support.

![image](https://cloud.githubusercontent.com/assets/1503131/25642437/c95193e0-2f67-11e7-90ff-66030d7f0d2a.png)

The output of `ansible-container --debug -version` shows a similar message:
![image](https://cloud.githubusercontent.com/assets/1503131/25642452/ec555b42-2f67-11e7-9ec7-395869d7d4ea.png)

That server has docker installed and is running docker containers. I'm sure that pip installed ansible-container correctly (or at least it claimed to). What is causing this error?

**Comment by brockbackups** [comment]
I am getting the same

**Comment by chouseknecht** [comment]
@Sean-Brown 

You need to have the Python module `docker>=2.1` installed. You can either install it manually, or run `pip install ansible-container[docker]`, as suggested by the error message.

After running `ansible-container init`, you'll need to modify the `container.yml` file, and define a service. Because there are no services defined in the sample file, it's throwing the error `AttributeError: 'function' object has no attribute 'get'`.

**Comment by Sean-Brown** [comment]
Thanks @chouseknecht `pip install ansible-container[docker]` did the trick. The error message confused me because I copied it verbatim (`pip install ansible-container==0.9.0.0[docker]`) and it did not run:
> Could not find a version that satisfies the requirement ansible-container==0.9.0.0[docker] (from versions: )
> No matching distribution found for ansible-container==0.9.0.0[docker]
