### ISSUE TITLE
Could not find a version that satisfies the requirement openshift==1.0.0 

### ISSUE THREAD

**Issue by jdoss** [ansible/ansible-container#487]
##### ISSUE TYPE
 - Bug Report

##### container.yml 
n/a

##### OS / ENVIRONMENT
```
Fedora 26 Alpha
```
##### SUMMARY

Running `sudo pip install ansible-container[docker,openshift]` results in Could not find a version that satisfies the requirement openshift==1.0.0.

##### STEPS TO REPRODUCE
1) `sudo pip install ansible-container[docker,openshift]`

##### EXPECTED RESULTS

`pip install ansible-container[docker,openshift]` works without error.

##### ACTUAL RESULTS
```
sudo pip install ansible-container[docker,openshift]
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting ansible-container[docker,openshift]
  Using cached ansible-container-0.9.0.0.tar.gz
Requirement already satisfied: Jinja2>=2.9 in /usr/lib/python2.7/site-packages (from ansible-container[docker,openshift])
Collecting PyYAML>=3.12 (from ansible-container[docker,openshift])
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied: requests>=2 in /usr/lib/python2.7/site-packages (from ansible-container[docker,openshift])
Collecting ruamel.yaml>=0.14.2 (from ansible-container[docker,openshift])
  Using cached ruamel.yaml-0.14.11-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from ansible-container[docker,openshift])
Collecting structlog[dev]>=16.1 (from ansible-container[docker,openshift])
  Using cached structlog-17.1.0-py2.py3-none-any.whl
Collecting docker>=2.1 (from ansible-container[docker,openshift])
  Using cached docker-2.2.1-py2.py3-none-any.whl
Collecting openshift==1.0.0 (from ansible-container[docker,openshift])
  Could not find a version that satisfies the requirement openshift==1.0.0 (from ansible-container[docker,openshift]) (from versions: 0.0.1)
No matching distribution found for openshift==1.0.0 (from ansible-container[docker,openshift])
```

**Comment by jdoss** [comment]
Pretty sure this is a typo somewhere. `pip search openshift` shows:
```...
openshift (0.0.1)                   - OpenShift python client
```
Looks like the version required is `0.0.1` not `1.0.0`.

**Comment by chouseknecht** [comment]
@jdoss, 

Thanks for using Ansible Container, and for taking the time to open an issue. 

This has been fixed in the `develop` branch. At the time of the 0.9 release the OpenShift module was not available in PyPi. So to get around that, we attempted to rely on dependency_links in setup.py to pull the repo from GitHub. However, that fails, and the modules does not install. 

You can either install it manually using `pip install openshift==0.0.1`, or download and install the latest from the Ansible Container repo.

I am going to go ahead and close this, as I think we've addressed it already.  If you still have trouble, please feel free to re-open, or start a new issue.

Thanks!

--Chris

**Comment by jdoss** [comment]
Cool sounds good. Thanks @chouseknecht!
