### ISSUE TITLE
the role 'kubernetes-modules' was not found

### ISSUE THREAD

**Issue by ehelms** [ansible/ansible-container#547]
##### ISSUE TYPE

 - Documentation Report

##### SUMMARY
Posting this as an issue/question since I did not see any updates in the docs for Openshift deploy with 0.9 and am wondering how to proceed. After generating the `openshift.yml` playbook to deploy my services I immediately hit the following:

```
ansible-playbook ansible-deployment/openshift.yml
```

```
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! the role 'kubernetes-modules' was not found in /home/ehelms/workspace/openshift/forklift/openshift/ansible-deployment/roles:/home/ehelms/workspace/openshift/forklift/openshift/roles:/home/ehelms/workspace/openshift/playbooks/roles:/home/ehelms/workspace/openshift/forklift/openshift/ansible-deployment

The error appears to have been in '/home/ehelms/workspace/openshift/forklift/openshift/ansible-deployment/openshift.yml': line 7, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    roles:
      - role: kubernetes-modules
        ^ here
```

In 0.3, everything was included in the generated role so I wasn't sure if that was simply missing in 0.9 at the moment or if I am supposed to include this role manually via `requirements.yml`.

**Comment by j00bar** [comment]
It should be `ansible.kubernetes-modules` I think. @chouseknecht, what was your intention here?

**Comment by chouseknecht** [comment]
The role is actually `ansible.kubernetes-modules`. We install it into the conductor container as `kubernetes-modules`.

The real question is, how to get the role into the user's environment so that the playbook just works? We could copy it out of the conductor container (or run `ansible-galaxy install`) to `ansible-deployment/roles`.

I'll add a step to just install it into `ansible-deployment/roles` so that it's available. I'll also change the name to `ansible.kubernetes-modules`, so that the origin of the role is more obvious.

And finally, I'll take a look at our docs and make updates. Pretty sure there's nothing in the `deploy` bits regarding this role, and how it enables the modules to work.

**Comment by j00bar** [comment]
I think installing it into ansible-deployment/roles is a good idea. The point is to have it executable outside of the conductor, someplace else entirely even. Thanks!!

**Comment by ehelms** [comment]
Thanks for the info, I updated my playbook to install via galaxy into ansible-deployment for the time being as well as updating the playbook to have the proper role name. 

One thing I did notice is that ansible-deployment appears to always be created owned by root:root which causes issues when running as my normal user on my laptop. Would you like a separate issue for this?
