### ISSUE TITLE
ansible-deployment/ directory is owned by root:root

### ISSUE THREAD

**Issue by ehelms** [ansible/ansible-container#557]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
When running `ansible-container --engine openshift deploy` an ansible-deployment/ directory is created along with a playbook for the openshift deployment (e.g. openshift.yml). Both of these are owned by root:root the first time they are created (I assume because they are created by the conductor container). When running as my normal user this is annoying because I cannot easily edit or install additional roles into that directory without having to update the perms.

**Comment by ryansb** [comment]
I believe this is fixed in 0.9.1 - what version of ansible-container do you have installed?

**Comment by ehelms** [comment]
I am running from head of develop (granted I adjusted my playbook to set these perms for me so let me re-test removing that).

**Comment by ryansb** [comment]
Thanks - I thought we'd fixed that but there may have been a regression. I'll test this afternoon and try to make a fix.

**Comment by chouseknecht** [comment]
@ryansb is this happening because we don't explicitly create the directory [here](https://github.com/ansible/ansible-container/blob/develop/container/docker/engine.py#L234), prior to bind mounting it to the conductor. If it doesn't exist, then the bind mount process creates it, I guess.

Seems like if we added the following to create the directory, it would get created with the right ownership:

```
if not os.path.exists(deployment_path):
    uid, gid = params.get('host_user_uid', 1), params.get('host_user_gid', 1)
    os.makedirs(deployment_path, 0o777)
```

**Comment by ryansb** [comment]
I think the default umask would be fine, since docker daemon is always going to be running as root, so it's going to have the permissions to do the reads/writes it wants. Inside the container, we write playbooks as the uid/gid of the container-invoking user [here](https://github.com/ansible/ansible-container/blob/4dbc7dabb02f723112cfcbc81028bc0af84c3197/container/core.py#L471) so inside that directory permissions should be correct.

**Comment by ryansb** [comment]
@ehelms PR #559 should fix it, would you like to try and see if it resolves your issue (you'll have to delete the root-owned directory first).
