### ISSUE TITLE
Can main.yaml be optional?

### ISSUE THREAD

**Issue by cdrage** [ansible/ansible-container#68]
Sometimes I'd like to build it without using the main.yaml file, either to use Ansible to deploy the containers with just a straight-up plain-jane nginx Docker container.

Could this be optional (warn the user?)

**Comment by gregdek** [comment]
Was about to file this exact issue. Thanks @cdrage!

Here's the issue. We want to make the move from docker-compose to this a noop if possible.

If we can allow an option for no main.yml, and just assume "hosts: all / gather_facts: false", then the user can  drop a docker-compose file into container.yml, and then ansible-container build && ansible-container run should literally just work.

**Comment by j00bar** [comment]
So, while working with @dustymabe yesterday, a conversation similar to this came up.

I'd always expected that Ansible Container can and should work with specialized non-base images from Docker Hub. There's a bug in the `run` command right now that expects all of the images being orchestrated to be built by Ansible Container, which in the case of a specialized non-base image, wouldn't be true. I'm going to fix that today.

I wouldn't recommend @gregdek 's approach though. The `build` process runs a `ansible-playbook --list-hosts` on your playbook to see what hosts got touched, and exports images based on what it finds. If `--list-hosts` reports that it touched your nginx container, it will export an image for it. I'd suggest you have `hosts: this-container-does-not-exist` just for a placeholder, so that you don't unnecessarily export the nginx image.

I'll report back when the `run` bug is fixed.
