### ISSUE TITLE
Conductor image naming convention

### ISSUE THREAD

**Issue by huge-metal-fan** [ansible/ansible-container#827]
##### ISSUE TYPE
 - Improvement

##### OS / ENVIRONMENT
```
alpine linux 3.7 armhf
ansible-container
```

##### SUMMARY
* Conductor image in its naming convention does not take into account CPU architecture. It's format is `container-conductor-$DISTRO-$TAG:$ANSIBLE_CONTAINER_VERSION`.
* Conductor image built via ./setup.py prebake got tag like container-conductor-{{ base image name }}. If base image name is huge-metal-fan/alpine.armhf:3.7 conductor image got tag container-conductor-huge-metal-fan/alpine.armhf:3.7 and it's impossible to push it to docker hub and use it in ansible-container build.

**Comment by j00bar** [comment]
Oh, fun. I've not seen anybody trying Ansible Container with non-x86. I really appreciate the bug report!

Because I just don't know, what's the proper naming convention to identify an image with architecture? Thanks!

**Comment by chouseknecht** [comment]
@huge-metal-fan 

Thanks for using Ansible Container, and for taking the time to file an issue. We always appreciate feedback. 

Here's the code that sets the prebake image name: https://github.com/ansible/ansible-container/blob/develop/container/docker/engine.py#L1110

I think what you're asking is for us to remove the `containter-conductor` string that gets prepended to the base image name.

Closing this, as I don't think we're inclined to change this, because there is no convention that will work for everyone or for every use case. As you can see in the [project code for pushing conductor images to Docker Hub](https://github.com/ansible/ansible-container/blob/develop/bakery.py#L28), we solve this by simply tagging the image with the Docker Hub user and repository name that fits our needs.
