### ISSUE TITLE
sudo pip install is bad

### ISSUE THREAD

**Issue by TrentonAdams** [ansible/ansible-container#973]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

sudo pip install is always a bad practise.  It can overwrite packages installed via the distribution package manager, breaking the entire python system, and resulting in a need to re-install the OS.

This should be removed, and virtualenv should always be used.  If I'm not mistaken `pip install` is fine too, but virtualenv will allow installation of software without worrying about conflicting versions of libraries.
```sudo pip install "ansible-container[docker,openshift]"```

I ran into these problems with pip myself.  After chatting on #python IRC I was told that "sudo pip install" is not a good idea.

**Comment by Voronenko** [comment]
Thank you for your report. Fixed in scope of #939

Fix should be available in next pypi release.

At a moment workaround would be using virtualenv and downgrading pip to 9.0.3
OR you might give a shot to unofficial sa-ansible-container builds for develop branch of the project @  https://pypi.org/project/sa-ansible-container/#history
